CREATE TABLE digital_lifestyle_metrics (
    date DATE,
    user_id VARCHAR(20),
    age INT,
    gender VARCHAR(20),
    city VARCHAR(80),
    occupation VARCHAR(80),
    device VARCHAR(80),
    screen_time_hours DECIMAL(6, 2),
    social_media_hours DECIMAL(6, 2),
    productivity_hours DECIMAL(6, 2),
    entertainment_hours DECIMAL(6, 2),
    total_unlocks INT,
    total_notifications INT,
    total_battery_usage INT,
    sleep_hours DECIMAL(5, 2),
    steps INT,
    day_type VARCHAR(20),
    day_name VARCHAR(20),
    is_weekend BOOLEAN,
    productive_ratio DECIMAL(6, 3),
    wellbeing_score DECIMAL(5, 2),
    screen_time_band VARCHAR(20),
    PRIMARY KEY (date, user_id)
);
